// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "test.h"
#include <stdio.h>

static void UpdateSmoke(float f)
{
	SmokeWeight = f;
}

void SliderInterface::cb_DensitySlider_i(Fl_Value_Slider*, void*) {
  UpdateSmoke(DensitySlider->value());
  printf("%6.4lf", SmokeWeight);
}
void SliderInterface::cb_DensitySlider(Fl_Value_Slider* o, void* v) {
  ((SliderInterface*)(o->parent()->parent()->user_data()))->cb_DensitySlider_i(o,v);
}

SliderInterface::SliderInterface() {
  { window = new Fl_Double_Window(408, 365, "window");
    window->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(15, 25, 380, 325, "Smoke Sliders");
      o->box(FL_ENGRAVED_FRAME);
      o->color(FL_GRAY0);
      { DensitySlider = new Fl_Value_Slider(90, 40, 285, 25, "Density");
        DensitySlider->type(1);
        DensitySlider->minimum(0.01);
        DensitySlider->maximum(0.2);
        DensitySlider->value(0.05);
        DensitySlider->slider_size(0.161616);
        DensitySlider->callback((Fl_Callback*)cb_DensitySlider);
        DensitySlider->align(Fl_Align(FL_ALIGN_LEFT));
        DensitySlider->when(FL_WHEN_RELEASE);
      } // Fl_Value_Slider* DensitySlider
      o->end();
    } // Fl_Group* o
    window->end();
  } // Fl_Double_Window* window
}

void SliderInterface::make_window() {
  window->show();
}
