// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef test_h
#define test_h
#include "FL/Fl.H"
#include "FL/Fl_Double_Window.H"
#include "FL/Fl_Group.H"
#include "FL/Fl_Value_Slider.H"
#include "main.h"

class SliderInterface {
public:
  SliderInterface();
  float getSliderValue();
  Fl_Double_Window *window;
  Fl_Value_Slider *DensitySlider;
private:
  inline void cb_DensitySlider_i(Fl_Value_Slider*, void*);
  static void cb_DensitySlider(Fl_Value_Slider*, void*);
public:
  void make_window();
};
#endif
